# Generated by Django 5.1.1 on 2024-09-18 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0003_track_sptfy_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='artists',
            new_name='artist',
        ),
    ]
