# Generated by Django 5.1.1 on 2024-09-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0005_album_image_url_album_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
