# Generated by Django 5.1.1 on 2024-09-22 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0010_alter_favourite_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together=set(),
        ),
    ]
